// packages/gatsby/src/pages/index.tsx
import * as React from "react"
import { PageProps, Link, graphql } from "gatsby"
import { css } from "@emotion/react"
import Layout from "../components/layout"
import Seo from "../components/seo"

type DataProps = {
  allZone: {
    nodes: [
      {
        categories: [{ name: string; catId: string }]
        topic: string
      }
    ]
  }
}


const style = css`
.zone {
  display: grid;
  grid-template-columns: repeat(4, 17rem);
  column-gap: 1rem;
}
.zone__topic {
  grid-column: 1 / -1;;
}
`

const UsingTypescript: React.FC<PageProps<DataProps>> = ({
  data,
  location
}) => {
  return (
    <Layout title="rmov" location={location}>
      <Seo title="Using TypeScript" />
      <main css={style}>
        {data.allZone.nodes.map(node => (
          <section className="zone" key={node.topic}>
            <h2 className="zone__topic">{node.topic}</h2>
            {node.categories.map(cat => (
              <Link to={`category/${cat.catId}`} className="zone__node" key={cat.catId}>
                <h3 className="zone__node-title">{cat.name}</h3>
              </Link>
            ))}
          </section>
        ))}
      </main>
    </Layout>
  )
}
export default UsingTypescript

export const query = graphql`
  {
    allZone {
      nodes {
        categories(removeRegExp: "測試區|密室") {
          name
          catId
        }
        topic
      }
    }
  }
`

// packages/ui/pages/index.vue
<template>
  <main>
    <section v-for="zone in zones" :key="zone.topic" class="zone">
      <h2 class="zone__topic">{{zone.topic}}</h2>
      <NuxtLink class="zone__node" :to="`${encodeURIComponent(node)}`" :key="node.title" v-for="node in zone.sourceNodes">
        <h3 class="zone__node-title">{{node}}</h3>
      </NuxtLink>
    </section>
  </main>
</template>

<script>
export default {
  async asyncData ({ $content }) {
    const page = await $content('theads').fetch()
    const zones = page.entities.zones

    return {
      zones
    }
  }
}
</script>

<style lang="scss" scoped>
.zone {
  display: grid;
  grid-template-columns: repeat(4, 8rem);
  column-gap: 1rem;
}
.zone__topic {
  grid-column: 1 / -1;;
}

</style>
